In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df =sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [3]:
df.shape

(344, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [5]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [8]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [9]:
df['sex'] = pd.get_dummies(df['sex'], drop_first=True)

In [10]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g    sex  
0       3750.0   True  
1       3800.0  False  
2       3250.0  False  
4       3450.0  False  
5       3650.0   True

In [11]:
df['sex'] = df['sex'].astype(int)

In [12]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g  sex  
0       3750.0    1  
1       3800.0    0  
2       3250.0    0  
4       3450.0    0  
5       3650.0    1

In [13]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [14]:
island = pd.get_dummies(df['island'] , drop_first=True)

In [15]:
island

Dream  Torgersen
0    False       True
1    False       True
2    False       True
4    False       True
5    False       True
..     ...        ...
338  False      False
340  False      False
341  False      False
342  False      False
343  False      False

[333 rows x 2 columns]

In [16]:
island['Dream'] = island['Dream'].astype(int)
island['Torgersen'] = island['Torgersen'].astype(int)

In [17]:
island

Dream  Torgersen
0        0          1
1        0          1
2        0          1
4        0          1
5        0          1
..     ...        ...
338      0          0
340      0          0
341      0          0
342      0          0
343      0          0

[333 rows x 2 columns]

In [18]:
df = pd.concat([df , island] , axis = 1)

In [19]:
df = df.drop(['island'] , axis=1)

In [20]:
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex  \
0  Adelie            39.1           18.7              181.0       3750.0    1   
1  Adelie            39.5           17.4              186.0       3800.0    0   
2  Adelie            40.3           18.0              195.0       3250.0    0   
4  Adelie            36.7           19.3              193.0       3450.0    0   
5  Adelie            39.3           20.6              190.0       3650.0    1   

   Dream  Torgersen  
0      0          1  
1      0          1  
2      0          1  
4      0          1  
5      0          1

In [21]:
y = df.species
x= df.drop(['species'], axis=1)
y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [22]:
y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [25]:
print('x_train', x_train. shape)
print('X_test',x_test. shape)
print("Y_train", y_train. shape)
print('Y_test',y_test.shape)

x_train (233, 7)
X_test (100, 7)
Y_train (233,)
Y_test (100,)


In [26]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier (n_estimators = 5, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [27]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [28]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

In [29]:
cm =confusion_matrix(y_test, y_pred)
print(cm)

[[48  0  0]
 [ 1 15  0]
 [ 1  0 35]]


In [30]:
accuracy_score(y_test, y_pred)

0.98

In [31]:
print(classification_report (y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.94      0.97        16
           2       1.00      0.97      0.99        36

    accuracy                           0.98       100
   macro avg       0.99      0.97      0.98       100
weighted avg       0.98      0.98      0.98       100



In [33]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier (n_estimators = 7, criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [34]:
y_pred = classifier. predict (x_test)

In [37]:
accuracy_score(y_test, y_pred)

0.98