#Python Numpy Library

In [2]:
import numpy as np

In [3]:
myarr=np.array([3,6,32,8])

In [4]:
myarr

array([ 3,  6, 32,  8])

In [9]:
myarr=np.array([3,6,30,8],np.int32)

In [17]:
myarr[2]

30

In [19]:
myarr=np.array([[3,6,30,8]],np.int32)

In [29]:
myarr[0,2]

30

In [33]:
myarr.shape

(1, 4)

In [35]:
myarr.dtype

dtype('int32')

Array Creation:Conversion from other python structure

In [37]:
listarray=np.array([[1,2,3],[4,5,6],[6,8,4]])

In [39]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [6, 8, 4]])

In [41]:
listarray.dtype

dtype('int32')

In [43]:
listarray.size

9

In [45]:
np.array({30,40,50,60})

array({40, 50, 60, 30}, dtype=object)

Array Creation : Intrinsic numpy creation objects

In [47]:
zeros=np.zeros((2,5))

In [49]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
zeros.dtype

dtype('float64')

In [55]:
rng=np.arange(15)

In [57]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
lspace=np.linspace

In [71]:
lspace=np.linspace(1,25,100)

In [73]:
lspace

array([ 1.        ,  1.24242424,  1.48484848,  1.72727273,  1.96969697,
        2.21212121,  2.45454545,  2.6969697 ,  2.93939394,  3.18181818,
        3.42424242,  3.66666667,  3.90909091,  4.15151515,  4.39393939,
        4.63636364,  4.87878788,  5.12121212,  5.36363636,  5.60606061,
        5.84848485,  6.09090909,  6.33333333,  6.57575758,  6.81818182,
        7.06060606,  7.3030303 ,  7.54545455,  7.78787879,  8.03030303,
        8.27272727,  8.51515152,  8.75757576,  9.        ,  9.24242424,
        9.48484848,  9.72727273,  9.96969697, 10.21212121, 10.45454545,
       10.6969697 , 10.93939394, 11.18181818, 11.42424242, 11.66666667,
       11.90909091, 12.15151515, 12.39393939, 12.63636364, 12.87878788,
       13.12121212, 13.36363636, 13.60606061, 13.84848485, 14.09090909,
       14.33333333, 14.57575758, 14.81818182, 15.06060606, 15.3030303 ,
       15.54545455, 15.78787879, 16.03030303, 16.27272727, 16.51515152,
       16.75757576, 17.        , 17.24242424, 17.48484848, 17.72

In [75]:
 lspace=np.linspace(1,25,5)

In [77]:
lspace

array([ 1.,  7., 13., 19., 25.])

In [83]:
emp=np.empty((4,6))

In [85]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921822e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 8.01089062e-307,
        1.02359848e-306, 1.60219035e-306, 1.60220393e-306],
       [1.05700515e-307, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 1.69105613e-306]])

In [89]:
emp_like = np.empty_like(lspace)

In [91]:
emp_like

array([ 1.,  7., 13., 19., 25.])

In [93]:
ide=np.identity(45)

In [95]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [97]:
ide.shape

(45, 45)

In [99]:
arr=np.arange(99)

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [103]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [109]:
arr=arr.ravel()

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [113]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [115]:
ar=np.array(x)

In [117]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [119]:
ar.sum(axis=0)

array([12,  8,  9])

In [121]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [123]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [125]:
ar.flat

In [127]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [129]:
arr.ndim

1

In [131]:
arr.size

99

In [133]:
arr.nbytes

396

In [137]:
one=np.array([1,3,4,634,2])

In [139]:
one.argmax()

3

In [141]:
one.argmin()

0

In [145]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [147]:
one.argmax(axis=0)

3

In [151]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [155]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [157]:
ar.reshape((9))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [159]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [161]:
ar2=np.array([[1,4,3],
              [4,0,6],
              [7,1,0]])

In [167]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [163]:
ar2

array([[1, 4, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [165]:
ar+ar2

array([[ 2,  6,  6],
       [ 8,  5, 12],
       [14,  2,  0]])

In [171]:
[80,60]+[30,60]

[80, 60, 30, 60]

In [173]:
ar*ar2

array([[ 1,  8,  9],
       [16,  0, 36],
       [49,  1,  0]])

In [175]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [177]:
ar.sum()

29

In [179]:
ar.min()

0

In [181]:
ar.max()

7

In [183]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [185]:
np.count_nonzero(ar)

8

In [187]:
ar[1,2]=0

In [189]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [191]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [193]:
ch_ar=[0,4,55,2]

In [201]:
import sys

In [207]:
py_ar = [1, 2, 3, 4, 5]

In [209]:
np_ar = np.array(py_ar)

In [211]:
sys.getsizeof(1)*len(py_ar)

140