In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [19]:
os.chdir(r'C:\Users\vigne\Desktop\WORK\DATASETS')

In [20]:
df=pd.read_csv('penguins.csv')

In [21]:
df.head()

num species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    1  Adelie  Torgersen            39.1           18.7              181.0   
1    2  Adelie  Torgersen            39.5           17.4              186.0   
2    3  Adelie  Torgersen            40.3           18.0              195.0   
3    4  Adelie  Torgersen             NaN            NaN                NaN   
4    5  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
3          NaN     NaN  2007  
4       3450.0  female  2007

In [22]:
df.shape

(344, 9)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   num                344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


In [24]:
df.isnull().sum()

num                   0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [25]:
df.dropna(inplace=True)

In [26]:
df.isnull().sum()

num                  0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [52]:
df.drop(['num'],axis=1,inplace=True)

In [53]:
#cat to num one hot encoding
df.sex.unique()

array(['male', 'female'], dtype=object)

In [54]:
pd.get_dummies(df['sex']).head()

female  male
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [55]:
sex= pd.get_dummies(df['sex'],drop_first=True)#1 male 0 female
sex.head()

male
0     1
1     0
2     0
4     0
5     1

In [56]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [57]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [58]:
island=pd.get_dummies(df['island'],drop_first=True)
island.head()

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [59]:
#concat
new_data=pd.concat([df,island,sex],axis=1)

In [60]:
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  year  Dream  Torgersen  male  
0       3750.0    male  2007      0          1     1  
1       3800.0  female  2007      0          1     0  
2       3250.0  female  2007      0          1     0  
4       3450.0  female  2007      0          1     0  
5       3650.0    male  2007      0          1     1

In [61]:
new_data.drop(['island','sex'],axis=1,inplace=True)

In [64]:
new_data.head(5)

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   year  Dream  Torgersen  male  
0  2007      0          1     1  
1  2007      0          1     0  
2  2007      0          1     0  
4  2007      0          1     0  
5  2007      0          1     1

In [65]:
#target variable
Y=new_data.species
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [66]:
Y.unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

In [67]:
Y=Y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [68]:
#drop species
new_data.drop('species',axis=1,inplace=True)
new_data.head(5)

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  year  Dream  \
0            39.1           18.7              181.0       3750.0  2007      0   
1            39.5           17.4              186.0       3800.0  2007      0   
2            40.3           18.0              195.0       3250.0  2007      0   
4            36.7           19.3              193.0       3450.0  2007      0   
5            39.3           20.6              190.0       3650.0  2007      0   

   Torgersen  male  
0          1     1  
1          1     0  
2          1     0  
4          1     0  
5          1     1

In [69]:
X=new_data

In [70]:
#splitting

In [71]:
from sklearn.model_selection import train_test_split

In [74]:
train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [76]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [78]:
print('X_train',X_train.shape)
print('X_test',X_test.shape)
print('Y_train',Y_train.shape)
print('Y_test',Y_test.shape)


X_train (233, 8)
X_test (100, 8)
Y_train (233,)
Y_test (100,)


In [81]:
from sklearn.ensemble import RandomForestClassifier

In [83]:
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)

In [84]:
classifier.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [86]:
#pred
Y_pred=classifier.predict(X_test)
Y_pred

array([0, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0,
       1, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0,
       2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 1, 2, 2, 2, 0,
       0, 1, 1, 0, 2, 0, 1, 0, 2, 0, 2, 2], dtype=int64)

In [87]:
#cm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [88]:
cm=confusion_matrix(Y_test,Y_pred)

In [89]:
print(cm)

[[48  0  0]
 [ 0 18  0]
 [ 0  0 34]]


In [90]:
accuracy_score(Y_test,Y_pred)

1.0

In [91]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [104]:
#Gi
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=5,criterion='gini',random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=5, random_state=0)

In [105]:
Y_pred=classifier.predict(X_test)


In [106]:
accuracy_score(Y_test,Y_pred)

1.0